source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JanusXML_Example', :exclusive => true do
  pod 'JanusXML', :path => '../'
end

target 'JanusXML_Tests', :exclusive => true do
  pod 'JanusXML', :path => '../'

  
end
